# -*- coding: utf-8 -*-
"""Reporte automático_Jorge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13OEon6GUP10l3fktVuk2MiuYi-d4UDbO
"""

# -*- coding: utf-8 -*-
"""Copy of Consulta de usuarios 2026_Jorge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l1dMx27s3T_M80CdwEb83M0puYTmbTkE

**Import libreries**
"""

#Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage

"""**Loading data from Google Sheet**"""

# Function 1

def read_google_sheet(url, sheet_name):
  """
  This function reads a Google Sheets
  and converts it into a Pandas DataFrame

  Parameters:
  url is the Google Sheet's link
  sheet_name is the name of the sheet to be read

  """
  try:
      sheet_id = url.split("/d/")[1].split("/")[0]
      csv_url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
      df = pd.read_csv(csv_url)
      return df
  except Exception as e:
      print(f"Error al leer la hoja: {e}")
      return None

# Function 2

def get_previous_week():
    today = datetime.today()

    current_monday = today - timedelta(days=today.weekday())

    end_date = current_monday - timedelta(days=1)

    start_date = end_date - timedelta(days=6)

    return (
        start_date.replace(
            hour=0,
            minute=0,
            second=0,
            microsecond=0
        ),
        end_date.replace(
            hour=23,
            minute=59,
            second=59,
            microsecond=999999
        )
    )

# Function 3

def weekly_metrics(start_date, end_of_the_week):
  """
  This function calculates the weekly metrics for appointments.

  Parameters:
  start_date: The start date of the week.
  end_of_the_week: The end date of the week.
  """
  # Filter the DataFrame for dates within the specified week
  appointments_date = df_PILARES[(df_PILARES['Fecha'] >= start_date) & (df_PILARES['Fecha'] <= end_of_the_week)]

  daily_hourly_appointments = appointments_date.groupby(['Fecha', 'Hora']).size().unstack(fill_value=0)
  daily_hourly_appointments.columns = [f'Hora_{col}' for col in daily_hourly_appointments.columns]
  appointments_df = daily_hourly_appointments.reset_index()

  # Rename columns to match the desired output format
  appointments_df = appointments_df.rename(columns={
      'Hora_1': 'Primera_hora',
      'Hora_2': 'Segunda_hora',
      'Hora_3': 'Tercera_hora',
      'Hora_4': 'Cuarta_hora'
  })

  # Asegurar que existan las columnas antes de sumar
  cols = [c for c in ['Primera_hora', 'Segunda_hora', 'Tercera_hora', 'Cuarta_hora'] if c in appointments_df.columns]
  appointments_df['Total'] = appointments_df[cols].sum(axis=1)
  return appointments_df

# Function 4

def new_users_weekly(appointments_df, start_date, end_of_the_week):
  """
  This function calculates the new users for appointments.

  Parameters:
  appointments_df: DataFrame con las métricas
  start_date: The start date of the week.
  end_of_the_week: The end date of the week.
  """
  # Filter the DataFrame for dates within the specified week
  new_users_date = df_PILARES[(df_PILARES['Fecha'] >= start_date) & (df_PILARES['Fecha'] <= end_of_the_week)]

  # Count unique 'Folio' values for new users per date and hour
  new_users = new_users_date.groupby(['Fecha', 'Hora'])['Folio'].nunique().unstack(fill_value=0)

  total_unique_folios_in_week = new_users_date['Folio'].nunique()

  # Crear un DF (Folio y Actividad) filtrado por fecha
  usuarios_por_actividad = new_users_date.groupby('Actividad')['Folio'].count()
  usuarios_por_actividad_df = usuarios_por_actividad.reset_index()
  usuarios_por_actividad_df = usuarios_por_actividad_df.rename(columns={'Folio': 'Total'})

  # Contar las atenciones lúdicas y educativas usando .isin()
  ludicas = ['Curso de verano', ' IMSS - Bienestar', 'TAC (Tecnologías del Aprendizaje y el Conocimiento)', 'Talleres Lúdicos, recreativos y/o Pedagógicos', 'Verano divertido']

  actividades_ludicas_df = usuarios_por_actividad_df['Actividad'].isin(ludicas)

  atenciones_ludicas = usuarios_por_actividad_df.loc[actividades_ludicas_df, 'Total'].sum()
  atenciones_educativas = usuarios_por_actividad_df.loc[~actividades_ludicas_df, 'Total'].sum()


  #print(f"Total de folios únicos en la semana del {start_date.strftime('%d/%m/%y')} al {end_of_the_week.strftime('%d/%m/%y')} : {total_unique_folios_in_week}")
  print()
  #print(appointments_df)
  print()
  return appointments_df, total_unique_folios_in_week, atenciones_ludicas, atenciones_educativas

# Function 4

def new_users_weekly(appointments_df, start_date, end_of_the_week):
  """
  This function calculates the new users for appointments.

  Parameters:
  appointments_df: DataFrame con las métricas
  start_date: The start date of the week.
  end_of_the_week: The end date of the week.
  """
  # Filter the DataFrame for dates within the specified week
  new_users_date = df_PILARES[(df_PILARES['Fecha'] >= start_date) & (df_PILARES['Fecha'] <= end_of_the_week)]

  # Count unique 'Folio' values for new users per date and hour
  new_users = new_users_date.groupby(['Fecha', 'Hora'])['Folio'].nunique().unstack(fill_value=0)

  total_unique_folios_in_week = new_users_date['Folio'].nunique()

  # Crear un DF (Folio y Actividad) filtrado por fecha
  usuarios_por_actividad = new_users_date.groupby('Actividad')['Folio'].nunique()
  usuarios_por_actividad_df = usuarios_por_actividad.reset_index()
  usuarios_por_actividad_df = usuarios_por_actividad_df.rename(columns={'Folio': 'Total'})

  # Contar las atenciones lúdicas y educativas usando .isin()
  ludicas = ['Curso de verano', ' IMSS - Bienestar', 'TAC (Tecnologías del Aprendizaje y el Conocimiento)', 'Talleres Lúdicos, recreativos y/o Pedagógicos', ' Verano divertido']

  actividades_ludicas_df = usuarios_por_actividad_df['Actividad'].isin(ludicas)

  atenciones_ludicas = usuarios_por_actividad_df.loc[actividades_ludicas_df, 'Total'].sum()
  atenciones_educativas = usuarios_por_actividad_df.loc[~actividades_ludicas_df, 'Total'].sum()


  #print(f"Total de folios únicos en la semana del {start_date.strftime('%d/%m/%y')} al {end_of_the_week.strftime('%d/%m/%y')} : {total_unique_folios_in_week}")
  print()
  #print(appointments_df)
  print()
  return appointments_df, total_unique_folios_in_week, atenciones_ludicas, atenciones_educativas

#Function 5

def total_attentions_plot(appointments_df, start_date, end_of_the_week):
  """
  This function returns a graphic constructed with start, end dates and the
  total of atentions per day during the week.

  Parameters:
  start_date: The start date of the week.
  end_of_the_week: The end date of the week.
  """
  # Ensure 'Fecha' is in datetime format for plotting
  appointments_df['Fecha'] = pd.to_datetime(appointments_df['Fecha'])

  # Sort by date to ensure correct plotting order
  appointments_df = appointments_df.sort_values(by='Fecha').reset_index(drop=True)

  plt.figure(figsize=(6, 3))
  sns.barplot(x='Fecha', y='Total', data=appointments_df, palette="blend:#E8DCC4,#6A1B31", hue='Total', legend=False)
  plt.xticks(rotation=45)
  plt.title(f'Atenciones totales en la semana de {start_date.strftime("%d/%m/%y")} - {end_of_the_week.strftime("%d/%m/%y")}')
  plt.xlabel('Fecha')
  plt.ylabel('Atenciones totales')
  plt.grid(True, alpha=0.5)
  plt.xticks(rotation=45)
  plt.tight_layout()
  plt.savefig('atenciones_totales.png')
  # plt.show() # Se comenta esta línea para que no se muestre la gráfica en el notebook
  plt.close() # Cierra la figura para liberar memoria y evitar que se muestre en futuras celdas
  return

# Función 6

def send_report_email(appointments_df, total_unique_folios_in_week, atenciones_ludicas, atenciones_educativas, sender_email, sender_password, receiver_email, image_path='atenciones_totales.png'):
    try:
        # 1. Obtener credenciales de Google Colab Secrets
        #sender_email = userdata.get('EMAIL_USER')
        #sender_password = userdata.get('EMAIL_PASS')
        #receiver_email = userdata.get('EMAIL_DESTINO_1')

        # 2. Configurar estructura del mensaje
        msg = MIMEMultipart('related')
        msg['Subject'] = '📊 Reporte Semanal de Atenciones'
        msg['From'] = sender_email
        msg['To'] = receiver_email

        # 3. Convertir el DataFrame a tabla HTML
        df_html = appointments_df.to_html(index=False, border=1)

        # Cuerpo del mensaje en formato HTML
        html_content = f"""
        <html>
  <body>
    <h2>Reporte de Atenciones Semanales</h2>
    <p>A continuación se adjunta la tabla con el desglose del reporte:</p>
    {df_html}
    <p><b>Total de usuarios únicos atendidos en la semana:</b> {str(total_unique_folios_in_week)}</p>
    <br>
    <p><b>Total de atenciones educativas en la semana:</b> {str(atenciones_educativas)}</p>
    <br>
    <p><b>Total de atenciones lúdicas en la semana:</b> {str(atenciones_ludicas)}</p>
    <br>
    <p style="text-align: justify;"><b>NOTA</b></p>
    <p style="text-align: justify;"><b>Las actividades lúdicas consideradas en el cálculo se describen a continuación: Curso de verano, IMSS - Bienestar, TAC (Tecnologías del Aprendizaje y el \
    Conocimiento), Talleres Lúdicos, recreativos y/o Pedagógicos</b></p>
    <br>
    <p>Gráfica de atenciones adjunta en este correo.</p>
  </body>
</html>
        """

        msg_alternative = MIMEMultipart('alternative')
        msg.attach(msg_alternative)
        msg_alternative.attach(MIMEText(html_content, 'html'))

        # 4. Adjuntar la gráfica en la imagen
        with open(image_path, 'rb') as f:
            img_data = f.read()
            image = MIMEImage(img_data)
            image.add_header('Content-Disposition', 'attachment', filename=image_path)
            msg.attach(image)

        # 5. Enviar el correo a través del servidor SMTP de Gmail
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, receiver_email, msg.as_string())

        print("📧 ¡Reporte enviado exitosamente por correo! ")

    except Exception as e:
        print(f"❌ Error al enviar el correo: {e}")

datos_envio = [
    {
        # Datos Paola
        'data_url_key' : 'data_Paola',
        'correo_destinatario_key' : 'email_Paola',
        'correo_remitente_key' : 'EMAIL_USER',
        'password_key' : 'EMAIL_PASS'
    },

    {
        # Datos Jorge
        'data_url_key' : 'data_Jorge',
        'correo_destinatario_key' : 'email_Jorge',
        'correo_remitente_key' : 'EMAIL_USER',
        'password_key' : 'EMAIL_PASS'
    }
]


for envio_config in datos_envio:
  # Retrieve the keys from the current config
  current_data_url_secret = envio_config['data_url_key']
  current_email_dest_secret = envio_config['correo_destinatario_key']
  current_email_remit_secret = envio_config['correo_remitente_key']
  current_password_secret = envio_config['password_key']

  # Get the actual values from userdata
  current_url = os.getenv(current_data_url_secret)
  current_correo_destinatario = os.getenv(current_email_dest_secret)
  current_correo_remitente = os.getenv(current_email_remit_secret)
  current_password = os.getenv(current_password_secret)

  try:
    #Function 1 - Use current_url from the iteration
    df_PILARES = read_google_sheet(current_url, "ATENCIONES_2026")
    df_PILARES['Fecha'] = pd.to_datetime(df_PILARES['Fecha'], format='%d/%m/%y')

    # Function 2
    # Save variables star_date and end_date
    start_date, end_date = get_previous_week()

    #Function 3

    appointments_df = weekly_metrics(start_date, end_date)

    #Function 4
    appointments_df, total_unique_folios_in_week, atenciones_ludicas, atenciones_educativas = new_users_weekly(appointments_df, start_date, end_date)

    #Function 5
    total_attentions_plot(appointments_df, start_date, end_date)

    # Enviar correo: - Use the current values from the iteration
    send_report_email(appointments_df, total_unique_folios_in_week, atenciones_ludicas, atenciones_educativas, sender_email=current_correo_remitente, sender_password=current_password, receiver_email=current_correo_destinatario, image_path='atenciones_totales.png')

  except Exception as e:
    print(f"Error processing for URL: {current_url} and Recipient: {current_correo_destinatario}. Error: {e}")
