# -*- coding: utf-8 -*-
"""Reporte automático_Jorge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13OEon6GUP10l3fktVuk2MiuYi-d4UDbO
"""

# -*- coding: utf-8 -*-
"""Copy of Consulta de usuarios 2026_Jorge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l1dMx27s3T_M80CdwEb83M0puYTmbTkE

**Import libreries**
"""

#Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
from google.colab import userdata

"""**Loading data from Google Sheet**"""

# Function 1

def read_google_sheet(url, sheet_name):
  """
  This function reads a Google Sheets
  and converts it into a Pandas DataFrame

  Parameters:
  url is the Google Sheet's link
  sheet_name is the name of the sheet to be read

  """
  try:
      sheet_id = url.split("/d/")[1].split("/")[0]
      csv_url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
      df = pd.read_csv(csv_url)
      return df
  except Exception as e:
      print(f"Error al leer la hoja: {e}")
      return None

# Function 2

def get_previous_week ():
  """
  This function calculates the previous week's start and end dates.
  """
  # datetime represent date and hour
  # timedelta represents a time difference

  today = datetime.today()
  # This line extracts current date and hour

  current_monday = today - timedelta(days=today.weekday())
  # This line extract the monday's current week

  # Sema anterior
  end_date = current_monday - timedelta(days=1)
  # This line extract the last day of the previous week

  start_date = end_date - timedelta(days=6)
  # This line returns the first day of the previous week

  # Mantenemos las fechas como datetime para poder filtrar correctamente en Pandas
  return start_date.replace(hour=0, minute=0, second=0, microsecond=0), end_date.replace(hour=0, minute=0, second=0, microsecond=0)

# Function 3

def weekly_metrics(start_date, end_of_the_week):
  """
  This function calculates the weekly metrics for appointments.

  Parameters:
  start_date: The start date of the week.
  end_of_the_week: The end date of the week.
  """
  # Filter the DataFrame for dates within the specified week
  appointments_date = df_PILARES[(df_PILARES['Fecha'] >= start_date) & (df_PILARES['Fecha'] <= end_of_the_week)]

  daily_hourly_appointments = appointments_date.groupby(['Fecha', 'Hora']).size().unstack(fill_value=0)
  daily_hourly_appointments.columns = [f'Hora_{col}' for col in daily_hourly_appointments.columns]
  appointments_df = daily_hourly_appointments.reset_index()

  # Rename columns to match the desired output format
  appointments_df = appointments_df.rename(columns={
      'Hora_1': 'Primera_hora',
      'Hora_2': 'Segunda_hora',
      'Hora_3': 'Tercera_hora',
      'Hora_4': 'Cuarta_hora'
  })

  # Asegurar que existan las columnas antes de sumar
  cols = [c for c in ['Primera_hora', 'Segunda_hora', 'Tercera_hora', 'Cuarta_hora'] if c in appointments_df.columns]
  appointments_df['Total'] = appointments_df[cols].sum(axis=1)
  return appointments_df

# Function 4

def new_users_weekly(appointments_df, start_date, end_of_the_week):
  """
  This function calculates the new users for appointments.

  Parameters:
  appointments_df: DataFrame con las métricas
  start_date: The start date of the week.
  end_of_the_week: The end date of the week.
  """
  # Filter the DataFrame for dates within the specified week
  new_users_date = df_PILARES[(df_PILARES['Fecha'] >= start_date) & (df_PILARES['Fecha'] <= end_of_the_week)]

  # Count unique 'Folio' values for new users per date and hour
  new_users = new_users_date.groupby(['Fecha', 'Hora'])['Folio'].nunique().unstack(fill_value=0)

  total_unique_folios_in_week = new_users_date['Folio'].nunique()

  print(f"Total de folios únicos en la semana del {start_date.strftime('%d/%m/%y')} al {end_of_the_week.strftime('%d/%m/%y')} : {total_unique_folios_in_week}")
  print()
  print(appointments_df)
  print()
  return appointments_df, total_unique_folios_in_week

#Function 5

def total_attentions_plot(appointments_df, start_date, end_of_the_week):
  """
  This function returns a graphic constructed with start, end dates and the
  total of atentions per day during the week.

  Parameters:
  start_date: The start date of the week.
  end_of_the_week: The end date of the week.
  """
  # Ensure 'Fecha' is in datetime format for plotting
  appointments_df['Fecha'] = pd.to_datetime(appointments_df['Fecha'])

  # Sort by date to ensure correct plotting order
  appointments_df = appointments_df.sort_values(by='Fecha').reset_index(drop=True)

  plt.figure(figsize=(6, 3))
  sns.barplot(x='Fecha', y='Total', data=appointments_df, color='#7A1F3D')
  plt.title(f'Atenciones totales en la semana de {start_date.strftime("%d/%m/%y")} - {end_of_the_week.strftime("%d/%m/%y")}')
  plt.xlabel('Fecha')
  plt.ylabel('Atenciones totales')
  plt.grid(True, alpha=0.5)
  plt.xticks(rotation=45)
  plt.tight_layout()
  plt.savefig('atenciones_totales.png')
  plt.show()
  return



import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from google.colab import userdata

def send_report_email(appointments_df, total_unique_folios_in_week, image_path='atenciones_totales.png'):
    try:
        # 1. Obtener credenciales de Google Colab Secrets
        sender_email = userdata.get('EMAIL_USER')
        sender_password = userdata.get('EMAIL_PASS')
        receiver_email = userdata.get('EMAIL_DESTINO_1')

        # 2. Configurar estructura del mensaje
        msg = MIMEMultipart('related')
        msg['Subject'] = '📊 Reporte Semanal de Atenciones'
        msg['From'] = sender_email
        msg['To'] = receiver_email

        # 3. Convertir el DataFrame a tabla HTML
        df_html = appointments_df.to_html(index=False, border=1)

        # Cuerpo del mensaje en formato HTML
        html_content = f"""
        <html>
  <body>
    <h2>Reporte de Atenciones Semanales</h2>
    <p>A continuación se adjunta la tabla con el desglose del reporte:</p>
    {df_html}
    <p><b>Total de folios únicos en la semana:</b> {str(total_unique_folios_in_week)}</p>
    <br>
    <p>Gráfica de atenciones adjunta en este correo.</p>
  </body>
</html>
        """

        msg_alternative = MIMEMultipart('alternative')
        msg.attach(msg_alternative)
        msg_alternative.attach(MIMEText(html_content, 'html'))

        # 4. Adjuntar la gráfica en la imagen
        with open(image_path, 'rb') as f:
            img_data = f.read()
            image = MIMEImage(img_data)
            image.add_header('Content-Disposition', 'attachment', filename=image_path)
            msg.attach(image)

        # 5. Enviar el correo a través del servidor SMTP de Gmail
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, receiver_email, msg.as_string())

        print("📧 ¡Reporte enviado exitosamente por correo!")

    except Exception as e:
        print(f"❌ Error al enviar el correo: {e}")

# ==========================================
# Deploy script
# ==========================================


#Function 1
url = userdata.get('data_url_1')
df_PILARES = read_google_sheet(url, "ATENCIONES_2026")
df_PILARES['Fecha'] = pd.to_datetime(df_PILARES['Fecha'], format='%d/%m/%y')

# Function 2
# Save variables star_date and end_date
start_date, end_date = get_previous_week()

#Function 3

appointments_df = weekly_metrics(start_date, end_date)

#Function 4
appointments_df, total_unique_folios_in_week = new_users_weekly(appointments_df, start_date, end_date)

#Function 5
total_attentions_plot(appointments_df, start_date, end_date)

# Enviar correo:
#send_report_email(appointments_df, total_unique_folios_in_week, 'atenciones_totales.png')

